package entity;
// Generated Oct 23, 2021, 12:50:04 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VeryficationEmail generated by hbm2java
 */
@Entity
@Table(name = "veryfication_email", catalog = "qlbansua")
public class VeryficationEmail implements java.io.Serializable {

	private Integer id;
	private KhachHang khachHang;
	private String token;
	private String expireDate;

	public VeryficationEmail() {
	}

	public VeryficationEmail(KhachHang khachHang, String token, String expireDate) {
		this.khachHang = khachHang;
		this.token = token;
		this.expireDate = expireDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "khach_hang_id", nullable = false)
	public KhachHang getKhachHang() {
		return this.khachHang;
	}

	public void setKhachHang(KhachHang khachHang) {
		this.khachHang = khachHang;
	}

	@Column(name = "token", nullable = false)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "expire_date", nullable = false)
	public String getExpireDate() {
		return this.expireDate;
	}

	public void setExpireDate(String expireDate) {
		this.expireDate = expireDate;
	}

}
